name: Publish Docker Images

on:
  push:
    # branches:
    # - master
    # tags:
    # - v*

jobs:
  build-and-publish:
    name: Build and publish Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build and Publish to Registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: pyhf/pyhf-validation
        dockerfile: docker/Dockerfile
        tags: latest,root6.20.00,root6.20.00-python3.7
        tag_with_ref: ${{ startsWith(github.ref, 'refs/tags/') }}
    - name: Build and Publish to Registry with tag
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: pyhf/pyhf-validation
        dockerfile: docker/Dockerfile
        tags: latest,latest-stable,root6.20.00,root6.20.00-python3.7
        tag_with_ref: true 
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
